#!/usr/bin/env python3
"""Generate the native provider table from the Windows language resource script."""

import argparse
import hashlib
import pathlib
import re


def read_identifier_values(path: pathlib.Path) -> dict[str, int]:
    values: dict[str, int] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        match = re.fullmatch(r"\s*#define\s+(TXT_[A-Za-z0-9_]+)\s+([0-9]+)\s*", line)
        if match:
            values[match.group(1)] = int(match.group(2))
    return values


def decode_resource_string(token: str) -> str:
    assert token.startswith('"') and token.endswith('"')
    text = token[1:-1]
    result: list[str] = []
    index = 0
    escapes = {"a": "\a", "b": "\b", "f": "\f", "n": "\n", "r": "\r", "t": "\t", "v": "\v"}
    while index < len(text):
        char = text[index]
        if char == '"' and index + 1 < len(text) and text[index + 1] == '"':
            result.append('"')
            index += 2
        elif char != "\\":
            result.append(char)
            index += 1
        else:
            index += 1
            if index == len(text):
                raise ValueError("unterminated escape")
            escape = text[index]
            if escape in escapes:
                result.append(escapes[escape])
                index += 1
            elif escape in ('\\', '"', '?'):
                result.append(escape)
                index += 1
            elif escape == 'x':
                digits = []
                index += 1
                while index < len(text) and text[index] in "0123456789abcdefABCDEF":
                    digits.append(text[index])
                    index += 1
                if not digits:
                    raise ValueError("empty hexadecimal escape")
                result.append(chr(int("".join(digits), 16)))
            elif escape in "01234567":
                digits = [escape]
                index += 1
                for _ in range(2):
                    if index < len(text) and text[index] in "01234567":
                        digits.append(text[index])
                        index += 1
                result.append(chr(int("".join(digits), 8)))
            else:
                result.append(escape)
                index += 1
    return "".join(result)


def source_entries(resource: str, identifiers: dict[str, int]) -> list[tuple[int, str]]:
    entries: list[tuple[int, str]] = []
    blocks = re.findall(r"^STRINGTABLE(?:\s+DISCARDABLE)?\s*\nBEGIN\s*\n(.*?)^END\s*$", resource, re.MULTILINE | re.DOTALL)
    token = re.compile(r"([A-Za-z_][A-Za-z0-9_]*|\"(?:\\.|\"\"|[^\"])*\")")
    for block in blocks:
        tokens = token.findall(block)
        index = 0
        while index < len(tokens):
            name = tokens[index]
            index += 1
            if index == len(tokens) or not tokens[index].startswith('"'):
                raise ValueError(f"{name} is missing a string literal")
            text = ""
            while index < len(tokens) and tokens[index].startswith('"'):
                text += decode_resource_string(tokens[index])
                index += 1
            if name not in identifiers:
                raise ValueError(f"{name} has no TXT_ identifier")
            entries.append((identifiers[name], text))
    if not entries:
        raise ValueError("no STRINGTABLE entries found")
    if len({entry[0] for entry in entries}) != len(entries):
        raise ValueError("duplicate string identifiers in language resource")
    return entries


def cpp_literal(value: str) -> str:
    return '"' + "".join(f"\\x{byte:02X}" for byte in value.encode("utf-8")) + '"'


def generate(resource_path: pathlib.Path, identifiers_path: pathlib.Path, output_path: pathlib.Path) -> None:
    resource_bytes = resource_path.read_bytes()
    entries = source_entries(resource_bytes.decode("utf-8"), read_identifier_values(identifiers_path))
    digest = hashlib.sha256(resource_bytes).hexdigest()
    output = [
        "// Generated by code/language/generate_language_provider.py. Do not edit.",
        f"// Source: code/language/language.rc; SHA-256: {digest}",
        "#pragma once",
        "",
        "#include <array>",
        "",
        "namespace {",
        "struct LanguageNativeEntry { int Id; char const * Text; };",
        "inline constexpr std::array LanguageNativeEntries {",
    ]
    output.extend(f"\tLanguageNativeEntry{{{identifier}, {cpp_literal(text)}}}," for identifier, text in entries)
    output.extend([
        "};",
        "}",
        "",
        "inline char const * Language_Native_String(int id)",
        "{",
        "\tfor (LanguageNativeEntry const & entry : LanguageNativeEntries) {",
        "\t\tif (entry.Id == id) return(entry.Text);",
        "\t}",
        "\treturn(nullptr);",
        "}",
        "",
        "inline char const * Language_Native_Source_SHA256(void)",
        "{",
        f"\treturn(\"{digest}\");",
        "}",
        "",
    ])
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(output), encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--resource", type=pathlib.Path, required=True)
    parser.add_argument("--identifiers", type=pathlib.Path, required=True)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    args = parser.parse_args()
    generate(args.resource, args.identifiers, args.output)


if __name__ == "__main__":
    main()
